mysql:
    protocol: "tcp"
    host: "api.ikanned.com"
    port: "24407"
    username: "nxc"
    password: "Password1!"
    database: "nxc_networks"
redis:
    host: ""
    port: ""
    password: ""
etcd:
    host: "api.ikanned.com"
    port: "22379"
    username: ""
    password: ""
rpc:
    host: ""
    port: ""
    