# Please make sure the content of this file matches your server configuration.
# If the configuration is wrong, you will not be able to connect to the server.
db:
    host: "api.ikanned.com"
    port: 24407
    username: "test"
    password: "Passcode1!"
